-- Adicionar 14 novas colunas para comissões de gerente e superintendente na tabela payments.base-de-vendas
ALTER TABLE payments.base_de_vendas 
ADD COLUMN IF NOT EXISTS comissao_sinal_perc_gerente NUMERIC,
ADD COLUMN IF NOT EXISTS comissao_vgv_pre_chaves_perc_gerente NUMERIC,
ADD COLUMN IF NOT EXISTS comissao_extra_perc_gerente NUMERIC,
ADD COLUMN IF NOT EXISTS comissao_integral_sinal_gerente NUMERIC,
ADD COLUMN IF NOT EXISTS comissao_integral_vgv_pre_chaves_gerente NUMERIC,
ADD COLUMN IF NOT EXISTS comissao_integral_extra_gerente NUMERIC,
ADD COLUMN IF NOT EXISTS sinal_comissao_extra_vendedor_gerente NUMERIC,
ADD COLUMN IF NOT EXISTS comissao_sinal_perc_superintendente NUMERIC,
ADD COLUMN IF NOT EXISTS comissao_vgv_pre_chaves_perc_superintendente NUMERIC,
ADD COLUMN IF NOT EXISTS comissao_extra_perc_superintendente NUMERIC,
ADD COLUMN IF NOT EXISTS comissao_integral_sinal_superintendente NUMERIC,
ADD COLUMN IF NOT EXISTS comissao_integral_vgv_pre_chaves_superintendente NUMERIC,
ADD COLUMN IF NOT EXISTS comissao_integral_extra_superintendente NUMERIC,
ADD COLUMN IF NOT EXISTS sinal_comissao_extra_vendedor_superintendente NUMERIC;

-- Atualizar a view public.base_de_vendas para incluir as novas colunas
DROP VIEW IF EXISTS public.base_de_vendas;

CREATE VIEW public.base_de_vendas AS
SELECT 
  id,
  data_do_contrato,
  tipo_venda,
  data_sicaq,
  vlr_tabela,
  data_pagto,
  cliente,
  empreendimento,
  bl,
  unid,
  assinatura_cef,
  vlr_venda,
  origem,
  comissao_integral_extra,
  comissao_integral_vgv_pre_chaves,
  vlr_contrato,
  fluxo,
  comissao_sinal_perc,
  vendedor_parceiro,
  supervisor_coord_parceiro,
  entrada,
  recebido,
  receber,
  comissao_integral_sinal,
  gerente,
  comissao_extra_perc,
  comissao_vgv_pre_chaves_perc,
  diretor,
  superintendente,
  c_credito_baixada,
  c_credito_em_aberto,
  c_desconto_baixada,
  c_desconto_em_aberto,
  recebido_de_sinal,
  perc_desconto,
  periodo_id,
  created_at,
  sinal_comissao_extra_vendedor,
  perc_sinal_recebido,
  -- Novas colunas de gerente
  comissao_sinal_perc_gerente,
  comissao_vgv_pre_chaves_perc_gerente,
  comissao_extra_perc_gerente,
  comissao_integral_sinal_gerente,
  comissao_integral_vgv_pre_chaves_gerente,
  comissao_integral_extra_gerente,
  sinal_comissao_extra_vendedor_gerente,
  -- Novas colunas de superintendente
  comissao_sinal_perc_superintendente,
  comissao_vgv_pre_chaves_perc_superintendente,
  comissao_extra_perc_superintendente,
  comissao_integral_sinal_superintendente,
  comissao_integral_vgv_pre_chaves_superintendente,
  comissao_integral_extra_superintendente,
  sinal_comissao_extra_vendedor_superintendente
FROM payments.base_de_vendas;